platform :ios, '7.0'

target "Tarbar" do
    pod 'Masonry'
    pod 'WebViewJavascriptBridge', '~> 5.0'
    pod 'YYModel'
    pod 'pop', '~> 1.0'
    pod 'UICountingLabel'
    pod 'SDWebImage', '~>3.8'
#    pod 'MQTTKit', :git => 'https://github.com/jmesnil/MQTTKit.git'
end
