platform :ios, '8.0'

target 'swiftStyle' do
    use_frameworks!

#pod 'AFNetworking', '~> 3.0'
#    pod 'SVGKit', :git => 'https://github.com/linkedin-inc/SVGKit.git', :branch => '2.x'
#    pod 'CocoaLumberjack', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git', :tag => '2.4.0' #Required by SVGKit

    pod 'SnapKit', '~> 3.0.2'
    pod 'GPUImage'
    pod 'AMap2DMap', '4.3.0'
    pod 'AMapSearch', '4.2.0'
#    pod 'ZFPlayer'
    pod 'BMPlayer', :git => 'https://github.com/BrikerMan/BMPlayer.git'
    pod 'TTTAttributedLabel'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "3.0"
            configuration.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end
    end
end
